version: '3.8'  

services:  
  web:    
    build:  
      context: .   
      dockerfile: Dockerfile  
    ports:  
      - "8080:8080"  
    networks:  
      - network2  
    depends_on:  
      - db   

  db:  
    image: postgres:latest  
    container_name: postgres  
    expose:  
      - "5432"  
    environment:  
      POSTGRES_USER: "postgres"           # Corrected  
      POSTGRES_PASSWORD: "admin"           # Corrected  
      POSTGRES_DB: "HomeERP"               # Corrected  
    volumes:  
      - pgdata2:/var/lib/postgresql/data  
    networks:  
      - network2  

  pgadmin:  
    image: dpage/pgadmin4  
    restart: always  
    environment:  
      PGADMIN_DEFAULT_EMAIL: admin@example.com  
      PGADMIN_DEFAULT_PASSWORD: admin  
    ports:  
      - "1235:80"  
    networks:  
      - network2  
    depends_on:  
      - db  

networks:  
  network2:  
    driver: bridge  

volumes:  
  pgdata2: 
