version: '3.8'  

services:  
  web:    
    build:  
      context: . 
      dockerfile: Dockerfile
    environment:  
      DB_CONNECTION_STRING: Server=db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT} 
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}  
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
    ports:  
      - "8080:8080"
    networks:  
      - network
    depends_on:  
      - db 

  db:  
    image: postgres:latest
    container_name: postgres
    expose: 
      - "5432" 
    environment:  
      POSTGRES_DB: ${POSTGRES_DB} 
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}    
    volumes:  
      - pgdata:/var/lib/postgresql/data
    networks:  
      - network

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:  
      - minio_data:/data  
    environment:
      MINIO_ENDPOINT: ${MINIO_ENDPOINT} 
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}  
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}  
    command: server /data --console-address ":9001"
    networks:  
      - network

networks:  
  network:  
    driver: bridge

volumes:
  minio_data:  
  pgdata: